[project]
name = "note-to-flashcard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "keyring==25.6.0",
    "openai==1.63.0",
    "pillow==11.1.0",
    "pyinstaller==6.12.0",
    "toga==0.4.9",
]

